export function getTimeZoneName(zone: string, gmt: string): string {
  const zoneMappings: Record<string, string> = {
    "US/Alabama": "Central Time",
    "US/Alaska": "Alaska Time",
    "US/Arizona": "Mountain Time",
    "US/Arkansas": "Central Time",
    "US/California": "Pacific Time",
    "US/Colorado": "Mountain Time",
    "US/Connecticut": "Eastern Time",
    "US/Delaware": "Eastern Time",
    "US/Florida": "Eastern Time",
    "US/Georgia": "Eastern Time",
    "US/Hawaii": "Hawaii Time",
    "US/Idaho": "Mountain Time",
    "US/Illinois": "Central Time",
    "US/Indiana": "Eastern Time",
    "US/Iowa": "Central Time",
    "US/Kansas": "Central Time",
    "US/Kentucky": "Eastern Time",
    "US/Louisiana": "Central Time",
    "US/Maine": "Eastern Time",
    "US/Maryland": "Eastern Time",
    "US/Massachusetts": "Eastern Time",
    "US/Michigan": "Eastern Time",
    "US/Minnesota": "Central Time",
    "US/Mississippi": "Central Time",
    "US/Missouri": "Central Time",
    "US/Montana": "Mountain Time",
    "US/Nebraska": "Central Time",
    "US/Nevada": "Pacific Time",
    "US/New_Hampshire": "Eastern Time",
    "US/New_Jersey": "Eastern Time",
    "US/New_Mexico": "Mountain Time",
    "US/New_York": "Eastern Time",
    "US/North_Carolina": "Eastern Time",
    "US/North_Dakota": "Central Time",
    "US/Ohio": "Eastern Time",
    "US/Oklahoma": "Central Time",
    "US/Oregon": "Pacific Time",
    "US/Pennsylvania": "Eastern Time",
    "US/Rhode_Island": "Eastern Time",
    "US/South_Carolina": "Eastern Time",
    "US/South_Dakota": "Central Time",
    "US/Tennessee": "Central Time",
    "US/Texas": "Central Time",
    "US/Utah": "Mountain Time",
    "US/Vermont": "Eastern Time",
    "US/Virginia": "Eastern Time",
    "US/Washington": "Pacific Time",
    "US/West_Virginia": "Eastern Time",
    "US/Wisconsin": "Central Time",
    "US/Wyoming": "Mountain Time",

    // Existing mappings
    "US/Samoa": "Samoa Time",
    "US/East-Indiana": "Eastern Time",
    "US/Mountain": "Mountain Time",
    "US/Central": "Central Time",
    "US/Eastern": "Eastern Time",
    "America/Tijuana": "Pacific Time",
    "America/Chihuahua": "Mountain Time",
    "America/Mazatlan": "Mountain Time",
    "America/Bogota": "Eastern Time",
    "Europe/Paris": "Central European Time",
    "Europe/Berlin": "Central European Time",
    "Asia/Kolkata": "India Standard Time",
    "Asia/Shanghai": "China Standard Time"
  };

  const gmtMappings: Record<string, string> = {
    "GMT-11:00": "Samoa Time",
    "GMT-10:00": "Hawaii Time",
    "GMT-09:00": "Alaska Time",
    "GMT-08:00": "Pacific Time",
    "GMT-07:00": "Mountain Time",
    "GMT-06:00": "Central Time",
    "GMT-05:00": "Eastern Time",
    "GMT+00:00": "Greenwich Mean Time",
    "GMT+01:00": "Central European Time",
    "GMT+05:30": "India Standard Time",
    "GMT+08:00": "China Standard Time"
  };

  return zoneMappings[zone] || gmtMappings[gmt] || " ";
}
